- color: C2E0C6
  name: active
- color: C2E0C6
  name: blocked
- color: BFD4F2
  name: blocking
- color: BFD4F2
  name: breaking
- color: BFD4F2
  name: important
- color: C2E0C6
  name: maintenance
- color: EDEDED
  name: released
- color: EDEDED
  name: semantic-release
- color: C2E0C6
  name: waiting-for
