image:
  file: .gitpod.Dockerfile
tasks:
  - before: >-
      echo "export
      PUPPETEER_CACHE_DIR=/workspace/nuxt-mail/node_modules/.cache/puppeteer" >>
      /home/gitpod/.bashrc

      gitpod-env-per-project >> /home/gitpod/.bashrc && source /home/gitpod/.bashrc
    init: |-
      git config --global user.name "Sebastian Landwehr"
      git config diff.lfs.textconv cat
      git lfs pull
      yarn --frozen-lockfile
vscode:
  extensions:
    - https://sebastianlandwehr.com/vscode-extensions/karlito40.fix-irregular-whitespace-0.1.1.vsix
    - https://sebastianlandwehr.com/vscode-extensions/adrianwilczynski.toggle-hidden-1.0.2.vsix
    - octref.vetur@0.33.1
    - Tobermory.es6-string-html
    - zjcompt.es6-string-javascript
